name: biome

on:
  workflow_call:

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.9.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run biome check
        run: pnpm run check
